{
    'name': 'PTGN QMA & Audit',
    'version': '1.0.0',
    'summary': 'This module has been build for PT GAG Nikel QMA & Audit Team',
    'sequence': -100,
    'description': """This module has been build for PT GAG Nikel QMA & Audit team""",
    'category': 'Productivity',
    'author': 'Internusa Cipta Solusi Perdana (ICSP)',
    'maintainer': 'Internusa Cipta Solusi Perdana (ICSP)',
    'website': 'https://icsp.co.id',
    'depends': [],
    'data': [
        'security/ir.model.access.csv',
        'views/qma_daftar_induk_dokumen.xml',
        'views/qma_list_finding_internal_audit.xml',
        'views/qma_form_audit.xml',
        'views/menulist.xml',
        'views/assets.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}