{
    'name': 'Corporate Business Intelligence (BI)',
    'version': '14.0.0.1.0',
    'summary': 'Data Visualization Report For PT.GAG Nikel',
    'sequence': -100,
    'description': """This module has been build for PT GAG Nikel""",
    'category': 'Productivity',
    'author': 'Internusa Cipta Solusi Perdana (ICSP)',
    'maintainer': 'Internusa Cipta Solusi Perdana (ICSP)',
    'website': 'https://icsp.co.id',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/dashboard_view.xml',
        'views/web_asset_backend_template.xml',
        'views/config_ppm.xml',
        'views/config_production.xml',
        'views/config_sales.xml',
        'views/daftarmenu.xml',
    ],
    'demo': [],
    'qweb': [
        'static/xml/dashboard.xml',
        'static/xml/budgetinput.xml',
        'static/xml/sales.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}