{
    'name': 'PTGN PPM',
    'version': '14.0.0.1.0',
    'summary': 'Program Pengembangan & Pemberdayaan Masyarakat (PPM)',
    'sequence': -100,
    'description': """This module has been build for PT GAG Nikel PPM""",
    'category': 'Productivity',
    'author': 'Internusa Cipta Solusi Perdana (ICSP)',
    'maintainer': 'Internusa Cipta Solusi Perdana (ICSP)',
    'website': 'https://icsp.co.id',
    'depends': ['mail','mod_gag_uac','account'],
    'data': [
        'security/ir.model.access.csv',
        'wizards/payment_wizard_view.xml',
        'wizards/view_budget_approval.xml',
        'wizards/view_budget_transaction_approval.xml',
        'wizards/view_budget_cancelation.xml',
        'wizards/view_budget_transaction_cancelation.xml',
        'views/inputjeniskegiatan.xml',
        'views/inputkategorikegiatan.xml',
        'views/inputstatuskegiatan.xml',
        'views/inputpillargroup.xml',
        'views/forminputbudget.xml',
        'data/data.xml',
        'views/inputdatacoa.xml',
        'views/reportdatabudgetdetail.xml',
        'views/inputrealisasianggaran.xml',
        'views/formmasterlokasi.xml'
    ],
    'assets': {
            'web.assets_backend': [
                'mod_gag_ppm/static/src/js/dynamic_button.js',
            ],
    },
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}