{
    'name': 'Document Monitoring',
    'version': '14.0.0.1.0',
    'summary': 'Automated document and reporting housekeeping',
    'sequence': -100,
    'description': """This module has build for automated documentation process""",
    'category': 'Tools',
    'author': 'Bayu Sulistiawan',
    'maintainer': 'Internusa Cipta Solusi Perdana (ICSP)',
    'website': 'https://icsp.co.id',
    'depends': ['base','mail','web', 'hr', 'board'],
    'data': [
        'security/odm_groups.xml',
        'wizards/send_document_email_wizard.xml',
        'wizards/reporting_type_delete_wizard.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/mail_activity_data.xml',
        'data/cron_jobs.xml',
        'views/view_document_configuration.xml',
        'views/view_document_type.xml',
        'views/docmon_mail_server.xml',
        'views/docmon_report_submission.xml',
        'views/report_ticket_template.xml',
        'views/report_external_receipt.xml',
        'views/report_docmon.xml',
        'views/dashboard.xml',
        'views/reportreview.xml',
        'views/completion_report.xml',
        'views/odm_report_attachment_file_kanban.xml',
        'views/email_log_views.xml',
        'views/menu_views.xml',
        'views/assets.xml',
    ],
    'qweb': [
        'static/src/xml/completion_report_qweb.xml',
    ],
    'assets': {
        'web.assets_qweb': [
            'odm_report_scheduler/static/src/xml/completion_report_qweb.xml',
        ],
    },
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}