{
    'name': 'PTGN Corsec & Legal',
    'version': '1.0.0',
    'summary': 'This module has been build for PT GAG Nikel Corsec & Legal Team',
    'sequence': -100,
    'description': """This module has been build for PT GAG Nikel Corsec & Legal team""",
    'category': 'Productivity',
    'author': 'Internusa Cipta Solusi Perdana (ICSP)',
    'maintainer': 'Internusa Cipta Solusi Perdana (ICSP)',
    'website': 'https://icsp.co.id',
    'depends': ['base', 'mail', 'bus'],
    'data': [
        'security/ir.model.access.csv',
        'views/corsec_list_akta_notaris.xml',
        'views/corsec_daftar_bod_boc.xml',
        'views/corsec_daftar_izin.xml',
        'views/corsec_risalah_rapat_direksi.xml',
        'views/corsec_risalah_rapat_komisaris.xml',
        'views/corsec_doc_request.xml',
        'views/menulist.xml',
        'views/assets.xml',
        'data/check_doc_expiry.xml'
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}