{
    'name': 'PTGN HC, GA & ICT',
    'version': '1.0.0',
    'summary': 'This module has been build for PT GAG Nikel HC, GA & ICT Team',
    'sequence': -100,
    'description': """This module has been build for PT GAG Nikel HC, GA & ICT team""",
    'category': 'Productivity',
    'author': 'Internusa Cipta Solusi Perdana (ICSP)',
    'maintainer': 'Internusa Cipta Solusi Perdana (ICSP)',
    'website': 'https://icsp.co.id',
    'depends': ['hr_holidays'],
    'data': [
        'security/ir.model.access.csv',
        'views/hc_ticketing.xml',
        'views/hc_spplk.xml',
        'views/hc_risk_regist.xml',
        'views/hc_master_risk_type.xml',
        'views/hc_master_risk_level.xml',
        'views/hc_nppd.xml',
        'report/report_nppd.xml',
        'report/report_risk_register.xml',
        'views/menulist.xml',
        'views/assets.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'mod_gag_hc_ga_ict/static/src/css/style.css',
        ],
    },
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}