{
    'name': 'PTGN MPD',
    'version': '1.0.0',
    'summary': 'This module has been build for PT GAG Nikel MPD',
    'sequence': -100,
    'description': """This module has been build for PT GAG Nikel MPD team""",
    'category': 'Productivity',
    'author': 'Internusa Cipta Solusi Perdana (ICSP)',
    'maintainer': 'Internusa Cipta Solusi Perdana (ICSP)',
    'website': 'https://icsp.co.id',
    'depends': [],
    'data': [
        'security/ir.model.access.csv',
        'views/mpd_rencana_produksi.xml',
        'views/mpd_realisasi_produksi.xml',
        'views/mpd_berita_acara_serah_terima_pekerjaan.xml',
        'views/menulist.xml',
        'views/assets.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}