{
    'name': 'PTGN SCM',
    'version': '14.0.0.1.0',
    'summary': 'Office Automation',
    'sequence': 0,
    'description': """This module has been build for PT GAG Office Automation SCM""",
    'category': 'Tools',
    'author': 'Internusa Cipta Solusi Perdana (ICSP)',
    'maintainer': 'Internusa Cipta Solusi Perdana (ICSP)',
    'website': 'https://icsp.co.id',
    'depends': ['base','mail','purchase'],
    'data': [
        'security/ir.model.access.csv',
        'views/nomor_surat.xml',
        'views/scm_evaluasi_views.xml',
        'views/scm_evaluasi_summary_views.xml',
        'views/scm_evaluasi_kontraktor_views.xml',
        'reports/gagoa_scm_evaluasi_report.xml',
        'reports/gagoa_scm_evaluasi_report_view.xml',
        'views/menu_views.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}