{
    'name': 'PTGN Utility',
    'version': '14.0.0.1.0',
    'summary': 'This module has been build for PT GAG Nikel Utility and Maintenance team',
    'sequence': -100,
    'description': """This module has been build for PT GAG Nikel Utility and Maintenance team""",
    'category': 'Productivity',
    'author': 'Internusa Cipta Solusi Perdana (ICSP)',
    'maintainer': 'Internusa Cipta Solusi Perdana (ICSP)',
    'website': 'https://icsp.co.id',
    'depends': ['mail','mod_gag_uac','web'],
    'data': [
        'security/ir.model.access.csv',
        'wizards/view_electricity_audit_approval.xml',
        'wizards/view_electrical_consumption_rejected.xml',
        'wizards/view_tasklist_approval.xml',
        'wizards/view_acmaintenance_tasklist_rejection.xml',
        'wizards/view_ljjm_approval.xml',
        'wizards/view_ljjm_cancelation.xml',
        'wizards/view_maintenance_tasklist_approval.xml',
        'wizards/view_machinemaintenance_tasklist_rejection.xml',
        'views/checklistgroups.xml',
        'views/checkpointmapping.xml',
        'views/masterlocation.xml',
        'views/view_master_equipment.xml',
        'views/dailykwhinput.xml',
        'views/form_ac_maintenance_request.xml',
        'views/view_equipment_maintenance.xml',
        'views/form_maintenance_request.xml',
        'views/reportgensetperformance.xml',
        'views/reportgensetelectricity.xml',
        'views/view_master_setpoint.xml',
        'views/machineconditionreport.xml',
        'views/assets.xml',
        'data/data.xml',
        'views/menu_views.xml'
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}